KhaiDaiRestaurant/KhaiDaiRestaurant/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home, name='homepage'),
    path('menu/<slug:brand_slug>/', views.home, name='brand_wise'),
    path('User/', include('user.urls')),
    path('Menu/', include('menu.urls')),
    path('Menu/', include('order.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

KhaiDaiRestaurant/menu/urls.py
from django.urls import path
from .views import AddFoodItem,FoodModelDeleteView,FoodModelUpdateView,MenuDetailView

urlpatterns = [
    path('add_food/', AddFoodItem.as_view(), name='add_food'),
     path('editNote<int:pk>/', FoodModelUpdateView.as_view(), name='EditFood'),
    path('deleteNote<int:pk>/', FoodModelDeleteView.as_view(), name='deleteFood'),
    path('menu_detail/<int:food_item_id>/', MenuDetailView.as_view(), name='menu_detail'),
]

KhaiDaiRestaurant/menu/models.py
from django.db import models
from django.contrib.auth.models import User
from category.models import Category
# Create your models here.
class FoodItems(models.Model):
    name = models.CharField(max_length=50)
    category = models.ForeignKey(Category , on_delete=models.CASCADE, null = True , blank = True)
    price = models.DecimalField(max_digits=10, decimal_places=0)
    discounted_price = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True,default=0)
    description = models.TextField()
    image = models.ImageField(upload_to='menu/uploads', height_field=None, width_field=None, max_length=None,default='')
        
    def __str__(self):
            return self.name

class review(models.Model):
    post = models.ForeignKey(FoodItems, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=30)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
        
    def __str__(self):
        return f"reviwe by {self.name}"

class Order_history(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    purchase_date = models.DateTimeField(auto_now_add=True)
    FoodItems = models.ForeignKey(FoodItems,on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.user.first_name} borrowed this book name: {self.Book.title}"

KhaiDaiRestaurant/order/models.py
# models.py
from django.db import models
from menu.models import FoodItems
from django.contrib.auth.models import User

class CartItem(models.Model):
    Item_cart = models.ForeignKey('Cart', on_delete=models.CASCADE, related_name='cart_items' ,null=True, blank =True)  # Specify related_name
    food_item = models.ForeignKey(FoodItems, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    def get_total_price(self):
        return self.food_item.price * self.quantity
    
class Cart(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE, blank =True,null = True)
    items = models.ManyToManyField(CartItem)

    def get_total_price(self):
        return sum(item.get_total_price() for item in self.items.all())

class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    items = models.ManyToManyField(CartItem)
    total_cost = models.DecimalField(max_digits=10, decimal_places=2)

START_CHOICES = [
    ('★',1),
    ('★★',2),
    ('★★★',3),
    ('★★★★',4),
    ('★★★★★',5),
    ('★★★★★★',6),
    ('★★★★★★★',7),
]
class Review(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    food_item = models.ForeignKey(FoodItems, on_delete=models.CASCADE)
    rating = models.CharField(choices = START_CHOICES ,max_length=50)
    comment = models.TextField()

KhaiDaiRestaurant/menu/forms.py
from django import forms
from . import models

class FoodItemsForm(forms.ModelForm):
    class Meta:
        model = models.FoodItems
        fields = '__all__'
        
class reviewForm(forms.ModelForm):
    class Meta: 
        model = models.review
        fields = ['name', 'body']

KhaiDaiRestaurant/menu/views.py
from django.shortcuts import render
from django.views.generic import FormView
from . import forms
from django.urls import reverse_lazy
from . import models
from django.views.generic import DetailView
from django.views.generic import UpdateView,DeleteView
# Create your views here.

class AddFoodItem(FormView):
    template_name = 'Addform.html'
    form_class = forms.FoodItemsForm
    success_url = reverse_lazy('homepage')
    def form_valid(self, form):
            form.save()
            return super().form_valid(form)
    



class FoodModelUpdateView(UpdateView):
    model = models.FoodItems
    form_class = forms.FoodItemsForm
    template_name = "Addform.html"
    success_url = reverse_lazy('homepage')



class FoodModelDeleteView(DeleteView):
    model = models.FoodItems
    template_name = "delete.html"
    success_url = reverse_lazy('homepage')
    context_object_name = 'form'

class MenuDetailView(DetailView):
    model = models.FoodItems
    template_name = 'menu_detail.html'
    context_object_name = 'food_item'
    pk_url_kwarg = 'food_item_id'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['reviews'] = self.object.review_set.all()
        return context

KhaiDaiRestaurant/menu/templates/Addform.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<h1 class="text-center text-primary mt-5">ADD FOOD ITEM</h1>
<form style="width:50%; margin:auto" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}

    <button class="btn btn-warning" type="submit">Submit</button>
</form>

{% endblock %}

KhaiDaiRestaurant/menu/templates/delete.html
{% extends 'base.html' %} 
{% block content%}
<div style="width:50%; margin:auto;">
    <h1>Are you sure you want to delete this ? </h1>
  <form method="post">
    {% csrf_token %} 
    {{form}}
    <button class="btn btn-info" type="submit">Submit</button>
  </form>
</div>
{% endblock %}

KhaiDaiRestaurant/menu/templates/menu_detail.html
{% extends 'base.html' %}

{% block content %}
<img src="{{food_item.image.url}}" class="w-50 h-50" alt="" srcset="">
<h1 class="text-center text-info">Food Name:{{food_item.name}}</h1>
<h2 class="text-center text-secondary">Food Price:{{food_item.price}}</h2>
<p class="text-center text-dark">Description :{{food_item.description}}</p>
<h2>Reviews</h2>
  {% if reviews %}
    <ul>
      {% for review in reviews %}
        <li>
          Rating: {{ review.get_rating_display }} - {{ review.comment }}
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>No reviews yet.</p>
  {% endif %}
<a class="btn btn-info w-100 m-auto" aria-current="page" href="{% url 'add_to_cart' food_item.id %}">Add Cart</a>

{% endblock %}